/*
Enter your query here.
*/


SELECT ID , 'ROOT' FROM TREE WHERE P_ID IS NULL;

SELECT DISTINCT parent ,'INNER' FROM 
(SELECT P_ID as parent FROM TREE WHERE P_ID IS NOT NULL AND P_ID NOT IN(SELECT ID FROM TREE WHERE P_ID IS NULL)) as temp;

SELECT DISTINCT ID, 'LEAF' FROM TREE
WHERE ID NOT IN (SELECT DISTINCT P_ID FROM TREE WHERE P_ID IS NOT NULL);